<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMPZuYm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMPZuYm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKMPZuYm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKMPZuYm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKMPZuYm\App_KernelDevDebugContainer([
    'container.build_hash' => 'KMPZuYm',
    'container.build_id' => 'c553b42e',
    'container.build_time' => 1695899180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMPZuYm');
